flowchart LR

P[Probe] -->|Standardized result| A(Aggregation Engine)
P1[Probe] -->|Standardized result| A
P2[Probe] -->|Standardized result| A

A -.->|Ask for a timestamp| RTS(Third party timestamper)

P -.-> H[Agents registry]
P1 -.-> H
P2 -.-> H
A -.-> H

A -->|HTTP POST| B[FastAPI]
B -.->|Ask for a timestamp| RTS
B -->|Write| G[Database]
E[External source] -->|HTTP POST| B